#!/bin/sh

RED='\e[1;31m'
RESETCOLOR='\e[39;49m'
ERROR="$RED"'Error:'"$RESETCOLOR"

if [ "$(id -u)" -ne 0 ]; then
    printf "$ERROR Run this script as root or with the sudo command.\n"1>&2;tput init
    exit 1
fi

if [ "$(stat -c %d:%i /)" != "$(stat -c %d:%i /proc/1/root/.)" ]; then
    printf "$ERROR Running in chroot, ignore the snapshot creation request.\n"1>&2;tput init
    exit 1
fi

if ! command -v timeshift > /dev/null; then
    exit 1
fi

if grep kaisen-grub-btrfs < /proc/cmdline > /dev/null; then
    printf "$ERROR You have not booted from a snapshot. Aborting.\n" 1>&2;tput init
    exit 1
fi

SNAPSHOT=$(awk -F 'subvol=timeshift-btrfs/snapshots/' '{ print $2 }' /proc/cmdline | cut -d '/' -f1)

timeshift --yes --scripted --btrfs --restore --snapshot "$SNAPSHOT"
