#!/bin/bash

set -e

if [ -z "$2" ]; then
	if command -v grub-mkconfig > /dev/null
	then
		grub-mkconfig -o /boot/grub/grub.cfg || true
	fi
fi

# End automatically added section
# Automatically added by dh_installsystemd/13.10.1
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	# The following line should be removed in trixie or trixie+1
	deb-systemd-helper unmask 'grub-btrfs.service' >/dev/null || true

	# was-enabled defaults to true, so new installations run enable.
	if deb-systemd-helper --quiet was-enabled 'grub-btrfs.service'; then
		# Enables the unit on first installation, creates new
		# symlinks on upgrades if the unit file has changed.
		deb-systemd-helper enable 'grub-btrfs.service' >/dev/null || true
	else
		# Update the statefile to add new symlinks (if any), which need to be
		# cleaned up on purge. Also remove old symlinks.
		deb-systemd-helper update-state 'grub-btrfs.service' >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.10.1
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -z "${DPKG_ROOT:-}" ] && [ -d /run/systemd/system ]; then
		systemctl --system daemon-reload >/dev/null || true
		deb-systemd-invoke start 'grub-btrfs.service' >/dev/null || true
	fi
fi
# End automatically added section

if dpkg --compare-versions "$2" lt "4.12-5kaisen"; then
	if command -v grub-mkconfig > /dev/null
	then
		grub-mkconfig -o /boot/grub/grub.cfg || true
	fi
fi
