#!/bin/sh

set -e

PREREQ=""

prereqs() {
	echo "$PREREQ"
}

case $1 in
	prereqs)
		prereqs
		exit 0
	;;
esac

#Umount and remount /run for non read-only fs
umount /run
mount /run /run

#Check if the kaisen-grub-btrfs param is used to start in overlay
cat /proc/cmdline | grep kaisen-grub-btrfs > /dev/null || exit 0

if [ -x /usr/bin/btrfs -a -x /usr/bin/findmnt ] && \
	[ "$(findmnt -no FSTYPE -M /root)" = btrfs ] && \
	[ "$(btrfs property get /root ro)" = ro=false ]; then
	RAM="$(mktemp -dp /)"
	LOWER="$(mktemp -dp /)"
	UPPER=$RAM/upper
	OVERLAY=$RAM/overlay
	mount --move --no-mtab /root $LOWER
	mount -t tmpfs tmpfs $RAM
	mkdir -p $UPPER $OVERLAY
	mount -t overlay -o lowerdir=$LOWER,upperdir=$UPPER,workdir=$OVERLAY kaisen-grub-btrfs /root
fi
